---
title: Coding assignment (QSM class)
format:
  aea-pdf:
    keep-tex: true  
    journal:
      blinded: false
    indent: true
    citecolor: cyan
    linkcolor: cyan
    urlcolor: cyan
  aea-html: default
title-footnote: |
  Some footnotes on the title...
author-format: horizontal
author:
  - name: Hyoungchul Kim
    acknowledgements: | 
      The creator. We want to thank...
    affiliations:
      - name: The Wharton School, University of Pennsylvania
date: last-modified
articleurl: https://hchulkim.github.io
abstract: |
  This is a coding assignment for the QSM class.
keywords:
  - 3 to 6 keywords
bibliography: bibliography.bib  
---

# Use of programming language {#sec-use-of-programming-language}

For questions 1-6, I used `R` programming language. For other questions, I used `julia` programming language.

# Main data information {#sec-main-data-info}

I am using the 2022 LODES data from LEHD for my analysis. I obtained the raw data for Philadelphia county from the LEHD website and aggregated the data into tract-tract level. The process of cleaning the raw data was conducted using the source code: `src/R/01_clean_raw_data.R`.

Thus my primary analysis zone will be bilateral commuting flow within Philadelphia county for the year 2022. This means I will not be considering the flow where either the origin or the destination is outside of Philadelphia county.

## Q1 {.unnumbered}

As I mentioned in @sec-main-data-info, I obtained bilateral commuting flow data from LEHD LODES for the year 2022. I also downloaded supporting data on the locations of the tracts or blocks underlying the the data. I downloaded them in the `input` folder. You can also use `make raw` command to automatically download the raw data.[^1]

[^1]: Note that if you want to re-download the raw data, you must first use `make clean` command to remove the raw data in the `input` folder. Also note that if the original data was updated during the course of the semester, there is a likelihood that the new downloaded data might have different data structure that could affect the analysis.

## Q2 {.unnumbered}

For distance, I will use the distance between the centroids of the origin and destination tracts. For this, I used `sf` package and `tigris` package in R to calculate the distance between the centroids of the origin and destination tracts. The source code is available in `src/R/02_calculate_distance.R`. I also retained the fixed effects estimates in the Appendix.

## Q3 {.unnumbered}

I estimated the following linear model:

$$
\log(N_{ij}) = \theta_{i} + \lambda_{j} + \kappa d_{ij} + \varepsilon_{ij}\label{eq:distance}
$$

The estimation results are reported in the following table:

\clearpage

\begin{table}[!ht]
\centering
\caption{Estimation results}
\label{tab:est_results}
\input{tables/q3_linear_model.tex}
\end{table}
\footnotesize \textbf{Note}: This table presents estimates results of the equation \ref{eq:distance}. `distance_km` is the estimates of the semi-elasticity of the travel time (or distance). The values in the paranthesis in the table is the standard error.\vspace{3em}

\normalsize

You can see that the estimates of the semi-elasticity of the travel time (or distance) is sensible as it is negative (-0.07). This indicates that the travel time (or distance) has a negative correlation with the commuting flow.

# Q4 {.unnumbered}

After including all the $ij$ pairs and adding in zero commuting flows, I estimated the PPML model as follows:

$$
\log(\mathbb{E}[N_{ij}])= \theta_{i} + \lambda_{j} + \kappa d_{ij}\label{eq:ppml}
$$

The estimation results are reported in the following table (I also retained the fixed effects estimates in the Appendix):

\begin{table}[!ht]
\centering
\caption{Estimation results of the PPML model}
\label{tab:est_ppml}
\input{tables/q4_ppml.tex}
\end{table}
\footnotesize \textbf{Note}: This table presents estimates results of the equation \ref{eq:ppml}. `distance_km` is the estimates of the semi-elasticity of the travel time (or distance). The values in the paranthesis in the table is the standard error.\vspace{3em}

\normalsize

We can clearly see that the etimates of the semi-elasticity of the distance differs from the estimates in the previous question. The absolute size of the estimates is larger in the PPML model. Intuitively, I think this occurs because the PPML model incorporates the zero commuting flows that were neglected in the linear model. Since the zero commuting flows were not fully incorporated in the linear model, the estimates in the linear model were underestimating the effect of the travel-time cost on the commuting flow. 

# Q5 {.unnumbered}

1. For $ii$ pairs, we could add minimum distance from the centroid to the edge of the polygon geometry as the distance measure. While this is not a perfect measure, it still should work as a proxy for measuring the relative size of certain distance from traveling within the same tract. This also solves the zero distance issue. The only problem might be that this method could be bit ad-hoc and not consistent as we are just additional additional values only onto the $ii$ pairs and not consider the $ij$ pairs.

Using this method, I get the following estimates for linear and PPML models:

2. Another way would be to change the definition of the distance measure so that $ii$ pairs will not have zero values. For example, we re-define the distance between two polygons $A$ and $B$ as follows: distance from the centroid of $A$ to the centroid of $B$ plus the minimum distance from the centroid of $A$ to the edge of the polygon $A$ plut the minimum distance from the centroid of $B$ to the edge of the polygon $B$. With this new definition, $ii$ pairs will no longer have zero values since we would be using diameter of the polygon as the distance measure. 

Using this method, I get the following estimates for linear and PPML models:

\clearpage

## Introduction {#sec-intro}

I will show some examples of things you can easily do in quarto-format.

### Math

You can easily use latex math format in quarto.

This is in-line math: $x + y = 7$.

This is display-style math:
$$x + y = 7.$$

You can also use begin align style syntax:
\begin{align}
  x + y &= 7\label{eq:1}\\
  t + v &= 10.\label{eq:2}
\end{align}

This is equation \ref{eq:1}. This is equation \ref{eq:2}.

### Figures

Putting figures is easy in quarto. Use syntax like this:


## Related literature {#sec-lit}

Some citation example.

@schott: The famous international trade PNTR paper.

@berlin: Another famous paper in urban/spatial economics.

You can also put them inside the paranthesis: [@schott; @berlin].

Also, you can cite sections: @sec-lit.

## Methods {#sec-meth}

Some few rounds of Lorem ipsums to give you a sense of the format:

Lorem ipsum. Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.

Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.

Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.

## Results {#sec-result}

I am not sure you would need this, but in quarto, you can directly type codes and get their outputs (I know it's not pretty... You can customize it later if you want though):

```{r}

attitude |> head()

```

## Conclusion {#sec-conc}

## References {.unnumbered}

::: {#refs}
:::

## Appendix {.supplementary}

`{.supplementary}` works as an indicator that makes the section centered. Useful when starting an appendix or supplementary sections.

### Appendix A {.unnumbered}

Use `{.unnumbered}` to unnumber the section and give your own numbering.

### Appendix B {.unnumbered}

## Supplementary {.supplementary}
